# Run from C:\AWR_Insight_Portal_v2\
# py write_sar_master_parser.py
import os

content = (
"# modules/sar/sar_master_parser.py\n"
"import os, re, sys, glob\n"
"from datetime import date\n"
"\n"
"_PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))\n"
"sys.path.insert(0, os.path.join(_PROJECT_ROOT, 'common'))\n"
"\n"
"from logger_utils import get_logger\n"
"logger = get_logger('sar_master_parser')\n"
"\n"
"SAR_DIR     = os.path.join(_PROJECT_ROOT, 'sar_reports')\n"
"ARCHIVE_DIR = os.path.join(_PROJECT_ROOT, 'sar_archive')\n"
"\n"
"sys.path.insert(0, os.path.dirname(__file__))\n"
"\n"
"from sar_cpu_parser       import parse_sar_cpu,       insert_sar_cpu\n"
"from sar_memory_parser    import parse_sar_memory,    insert_sar_memory\n"
"from sar_swap_parser      import parse_sar_swap,      insert_sar_swap\n"
"from sar_disk_parser      import parse_sar_disk,      insert_sar_disk\n"
"from sar_network_parser   import parse_sar_network,   insert_sar_network\n"
"from sar_paging_parser    import parse_sar_paging,    insert_sar_paging\n"
"from sar_ctxswitch_parser import parse_sar_ctxswitch, insert_sar_ctxswitch\n"
"from sar_loadavg_parser   import parse_sar_loadavg,   insert_sar_loadavg\n"
"from sar_hugepage_parser  import parse_sar_hugepage,  insert_sar_hugepage\n"
"from sar_socket_parser    import parse_sar_socket,    insert_sar_socket\n"
"\n"
"_PARSERS = [\n"
"    ('CPU',            parse_sar_cpu,       insert_sar_cpu),\n"
"    ('Memory',         parse_sar_memory,    insert_sar_memory),\n"
"    ('Swap',           parse_sar_swap,      insert_sar_swap),\n"
"    ('Disk I/O',       parse_sar_disk,      insert_sar_disk),\n"
"    ('Network',        parse_sar_network,   insert_sar_network),\n"
"    ('Paging',         parse_sar_paging,    insert_sar_paging),\n"
"    ('Context Switch', parse_sar_ctxswitch, insert_sar_ctxswitch),\n"
"    ('Load Average',   parse_sar_loadavg,   insert_sar_loadavg),\n"
"    ('HugePages',      parse_sar_hugepage,  insert_sar_hugepage),\n"
"    ('Sockets',        parse_sar_socket,    insert_sar_socket),\n"
"]\n"
"\n"
"_SAR_BINARY_MAGIC = b'\\x96\\xd5\\x71\\x21'\n"
"\n"
"_DATE_PATTERNS = [\n"
"    re.compile(r'\\(([^)]+)\\)\\s+(\\d{2}/\\d{2}/\\d{4})'),\n"
"    re.compile(r'\\(([^)]+)\\)\\s+(\\d{4}-\\d{2}-\\d{2})'),\n"
"    re.compile(r'\\(([^)]+)\\)\\s+(\\d{2}/\\d{2}/\\d{2})\\b'),\n"
"]\n"
"\n"
"\n"
"def _is_binary_sar(filepath):\n"
"    try:\n"
"        with open(filepath, 'rb') as f:\n"
"            return f.read(4) == _SAR_BINARY_MAGIC\n"
"    except Exception:\n"
"        return False\n"
"\n"
"\n"
"def _wsl_path(windows_path):\n"
"    p = windows_path.replace('\\\\', '/').replace('\\\\', '/')\n"
"    import re as _re\n"
"    m = _re.match(r'^([A-Za-z]):/(.+)', p)\n"
"    if m:\n"
"        return '/mnt/{}/{}'.format(m.group(1).lower(), m.group(2))\n"
"    return p\n"
"\n"
"\n"
"def _convert_binary_sar(filepath):\n"
"    import shutil, subprocess\n"
"    filepath = os.path.abspath(filepath)\n"
"\n"
"    def _run(cmd, label):\n"
"        try:\n"
"            logger.info('Attempting {}'.format(label))\n"
"            result = subprocess.run(cmd, capture_output=True, text=True, timeout=120)\n"
"            output = result.stdout.strip()\n"
"            if not output:\n"
"                logger.warning('{} produced no output. stderr: {}'.format(label, result.stderr[:200]))\n"
"                return None\n"
"            lines = result.stdout.splitlines(keepends=True)\n"
"            logger.info('{} OK - {} lines'.format(label, len(lines)))\n"
"            return lines\n"
"        except FileNotFoundError:\n"
"            return None\n"
"        except subprocess.TimeoutExpired:\n"
"            logger.error('{} timed out'.format(label))\n"
"            return None\n"
"        except Exception as e:\n"
"            logger.error('{} error: {}'.format(label, e))\n"
"            return None\n"
"\n"
"    native_sar = shutil.which('sar')\n"
"    if native_sar:\n"
"        lines = _run([native_sar, '-A', '-f', filepath], 'native sar')\n"
"        if lines:\n"
"            return lines\n"
"\n"
"    wsl_exe = shutil.which('wsl')\n"
"    if wsl_exe:\n"
"        wsl_filepath = _wsl_path(filepath)\n"
"        check = subprocess.run([wsl_exe, 'which', 'sar'],\n"
"                               capture_output=True, text=True, timeout=10)\n"
"        if check.returncode == 0 and check.stdout.strip():\n"
"            lines = _run([wsl_exe, 'sar', '-A', '-f', wsl_filepath], 'WSL sar direct')\n"
"            if lines:\n"
"                return lines\n"
"            tmp = '/tmp/_sarconv_{}'.format(os.path.basename(filepath))\n"
"            cmd = 'TZ=Asia/Kolkata sadf -c {} > {} 2>/dev/null && TZ=Asia/Kolkata sar -A -f {}'.format(\n"
"                wsl_filepath, tmp, tmp)\n"
"            lines = _run([wsl_exe, 'bash', '-c', cmd], 'WSL sadf+sar IST')\n"
"            if lines:\n"
"                return lines\n"
"\n"
"    logger.error(\n"
"        'Cannot convert binary SAR file: {}\\n'\n"
"        'Option A: Install WSL + sysstat (sudo apt-get install sysstat)\\n'\n"
"        'Option B: On Linux server: sar -A -f <file> > output.txt'.format(\n"
"            os.path.basename(filepath)))\n"
"    return None\n"
"\n"
"\n"
"def extract_hostname_and_date(lines):\n"
"    hostname, sar_date = 'UNKNOWN_HOST', None\n"
"    for line in lines[:10]:\n"
"        for pat in _DATE_PATTERNS:\n"
"            m = pat.search(line)\n"
"            if m:\n"
"                hostname = m.group(1).strip()\n"
"                raw = m.group(2).strip()\n"
"                if re.match(r'\\d{4}-\\d{2}-\\d{2}', raw):\n"
"                    p = raw.split('-')\n"
"                    sar_date = '{}/{}/{}'.format(p[1], p[2], p[0])\n"
"                elif re.match(r'\\d{2}/\\d{2}/\\d{2}$', raw):\n"
"                    parts = raw.split('/')\n"
"                    sar_date = '{}/{}/20{}'.format(parts[0], parts[1], parts[2])\n"
"                else:\n"
"                    sar_date = raw\n"
"                break\n"
"        if sar_date:\n"
"            break\n"
"    if not sar_date:\n"
"        sar_date = date.today().strftime('%m/%d/%Y')\n"
"        logger.warning('SAR date not found - defaulting to today: {}'.format(sar_date))\n"
"    return hostname, sar_date\n"
"\n"
"\n"
"def process_sar_file(filepath, archive=False, hostname_override=None):\n"
"    filepath = os.path.abspath(filepath)\n"
"    if not os.path.exists(filepath):\n"
"        logger.error('SAR file not found: {}'.format(filepath))\n"
"        return False\n"
"\n"
"    fname = os.path.basename(filepath)\n"
"    logger.info('=' * 60)\n"
"    logger.info('Processing SAR: {}'.format(fname))\n"
"\n"
"    if _is_binary_sar(filepath):\n"
"        lines = _convert_binary_sar(filepath)\n"
"        if lines is None:\n"
"            return False\n"
"        logger.info('Binary SAR converted to text successfully')\n"
"    else:\n"
"        with open(filepath, 'r', encoding='utf-8', errors='replace') as f:\n"
"            lines = f.readlines()\n"
"\n"
"    hostname, sar_date = extract_hostname_and_date(lines)\n"
"\n"
"    if hostname_override and hostname_override.strip():\n"
"        logger.info('   Host    : {} (override - header had: {})'.format(\n"
"            hostname_override.strip(), hostname))\n"
"        hostname = hostname_override.strip()\n"
"    else:\n"
"        logger.info('   Host    : {}'.format(hostname))\n"
"    logger.info('   SAR date: {}'.format(sar_date))\n"
"\n"
"    failures = []\n"
"    for label, parse_fn, insert_fn in _PARSERS:\n"
"        try:\n"
"            records = parse_fn(lines, hostname, sar_date)\n"
"            insert_fn(records)\n"
"            logger.info('  OK {:<18} - {} rows'.format(label, len(records)))\n"
"        except Exception as e:\n"
"            logger.error('  FAIL {:<18} - {}'.format(label, e), exc_info=True)\n"
"            failures.append(label)\n"
"\n"
"    success = len(failures) == 0\n"
"    logger.info('SAR complete - {}'.format('OK' if success else 'Failures: {}'.format(failures)))\n"
"    return True\n"
"\n"
"\n"
"def scan_and_process(scan_dir=None):\n"
"    scan_dir = scan_dir or SAR_DIR\n"
"    if not os.path.isdir(scan_dir):\n"
"        logger.warning('SAR directory not found: {}'.format(scan_dir))\n"
"        return\n"
"    txt_files = glob.glob(os.path.join(scan_dir, '**', '*.txt'), recursive=True)\n"
"    if not txt_files:\n"
"        logger.warning('No SAR text files found in {}'.format(scan_dir))\n"
"        return\n"
"    for f in txt_files:\n"
"        process_sar_file(f, archive=True)\n"
"\n"
"\n"
"if __name__ == '__main__':\n"
"    import argparse\n"
"    p = argparse.ArgumentParser()\n"
"    p.add_argument('--file', default=None)\n"
"    p.add_argument('--scan', default=None)\n"
"    p.add_argument('--host', default=None)\n"
"    args = p.parse_args()\n"
"    if args.file:\n"
"        process_sar_file(args.file, hostname_override=args.host)\n"
"    else:\n"
"        scan_and_process(args.scan)\n"
)

dest = os.path.join("modules", "sar", "sar_master_parser.py")
with open(dest, "w", encoding="utf-8") as f:
    f.write(content)

written = open(dest, encoding="utf-8").read()
checks = {
    "hugepage import":  "from sar_hugepage_parser" in written,
    "socket import":    "from sar_socket_parser"   in written,
    "HugePages parser": "'HugePages'"               in written,
    "Sockets parser":   "'Sockets'"                 in written,
    "TZ=Asia/Kolkata":  "TZ=Asia/Kolkata"           in written,
    "2-digit year fix": "20{}'.format"              in written,
}
print("File: {}  ({} bytes)".format(os.path.abspath(dest), len(written)))
all_ok = True
for k, v in checks.items():
    print("  {} {}".format("OK" if v else "MISSING", k))
    if not v: all_ok = False
print()
print("SUCCESS" if all_ok else "ERROR - re-run script")
