{
 "title": "AWR Buffer Wait Statistics",
 "tags": [ "awr" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "portal_url", "label": "Portal URL", "query": "http://192.168.1.2:8000" },
   { "name": "grafana_url", "label": "Grafana URL", "query": "http://192.168.1.2:3000" },
   { "name": "ds", "label": "Data Source", "query": "postgres" },
   {
    "name": "dbname",
    "label": "Database",
    "query": "SELECT DISTINCT dbname FROM awr_buffer_wait_statistics ORDER BY dbname"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "SELECT DISTINCT instance FROM awr_buffer_wait_statistics WHERE dbname = '$dbname' ORDER BY instance"
   },
   {
    "name": "start_snap",
    "label": "Start Snap",
    "query": "SELECT begin_snap::text || ' - ' || to_char(snap_time,'YYYY-MM-DD HH24:MI:SS') FROM awr_buffer_wait_statistics WHERE dbname = '$dbname' AND instance = '$instance' ORDER BY begin_snap"
   },
   {
    "name": "end_snap",
    "label": "End Snap",
    "query": "SELECT begin_snap::text || ' - ' || to_char(snap_time,'YYYY-MM-DD HH24:MI:SS') FROM awr_buffer_wait_statistics WHERE dbname = '$dbname' AND instance = '$instance' ORDER BY begin_snap"
   }
  ]
 },
 "panels": [
  {
   "title": "Navigation Links",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<a href=\"${portal_url}/awr-trends?dbname=$dbname&instance=$instance&start_snap=$start_snap&end_snap=$end_snap\" target=\"awr_trends_tab\">⬅ Return to Navigation</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href=\"${portal_url}/awr-trends\" target=\"awr_trends_tab\">🔄 Reset Filters</a>"
   }
  },
  {
   "title": "Top 10 Buffer Wait Classes by Waits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "rawSql": "WITH top_classes AS (  SELECT b.class  FROM awr_buffer_wait_statistics b  \nWHERE '$dbname' != '' AND '$instance' != '' \nAND '$start_snap' != '' AND '$end_snap' != ''    \nAND b.dbname = '$dbname'    \nAND b.instance = '$instance'    \nAND b.begin_snap BETWEEN split_part('$start_snap',' - ',1)::int AND split_part('$end_snap',' - ',1)::int  \nGROUP BY b.class  \nORDER BY SUM(b.waits) DESC  LIMIT 10) \nSELECT  b.snap_time AT TIME ZONE 'Asia/Kolkata' AS time,  b.class,  b.waits \nFROM awr_buffer_wait_statistics b \nJOIN top_classes t ON t.class = b.class \nWHERE '$dbname' != '' AND '$instance' != '' \nAND '$start_snap' != '' AND '$end_snap' != ''   \nAND b.dbname = '$dbname'   AND b.instance = '$instance'   \nAND b.begin_snap BETWEEN split_part('$start_snap',' - ',1)::int AND split_part('$end_snap',' - ',1)::int \nORDER BY time;"
    }
   ]
  },
  {
   "title": "Total Wait Time (s) by Buffer Class (Top 10)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT class AS metric, SUM(total_wait_time_s) AS total_wait_time_s\nFROM awr_buffer_wait_statistics\nWHERE '$dbname' != '' AND '$instance' != '' AND '$start_snap' != '' AND '$end_snap' != ''\n  AND dbname = '$dbname'\n  AND instance = '$instance'\n  AND begin_snap BETWEEN split_part('$start_snap',' - ',1)::int AND split_part('$end_snap',' - ',1)::int\nGROUP BY class\nORDER BY total_wait_time_s DESC\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Avg Wait Time (ms) by Buffer Class (Top 10)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT class AS metric, AVG(avg_time_ms) AS avg_wait_time_ms\nFROM awr_buffer_wait_statistics\nWHERE '$dbname' != '' AND '$instance' != '' AND '$start_snap' != '' AND '$end_snap' != ''\n  AND dbname = '$dbname'\n  AND instance = '$instance'\n  AND begin_snap BETWEEN split_part('$start_snap',' - ',1)::int AND split_part('$end_snap',' - ',1)::int\nGROUP BY class\nORDER BY avg_wait_time_ms DESC\nLIMIT 10;"
    }
   ]
  }
 ]
}