-- ============================================================
-- Truncate mssql_dmv_snapshot and its 13 dependent delta tables --
-- clean slate now that the interval-enforcement fix is in place,
-- so the SQLWR report generator starts from a reliably-spaced
-- snapshot history rather than the irregular gaps left by many
-- manual test runs throughout this project's development.
--
-- Scoped to the DMV side only -- the Query Store side
-- (mssql_qs_interval and its dependents) was already confirmed
-- safe/idempotent (ON CONFLICT DO NOTHING, interval IDs come from
-- SQL Server's own Query Store, not generated by the collector) and
-- has no analogous issue, so it is deliberately left untouched here.
--
-- CASCADE handles all 13 dependent tables automatically -- no need
-- to enumerate them and risk missing one.
-- ============================================================

TRUNCATE TABLE mssql_dmv_snapshot RESTART IDENTITY CASCADE;

\echo 'mssql_dmv_snapshot and all 13 dependent delta tables truncated.'
SELECT count(*) AS remaining_snapshots FROM mssql_dmv_snapshot;
-- Expect 0 above.
